version: "3.8"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: node_heat
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
